# Generated by Django 4.0.2 on 2022-02-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestmandi',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
